### PR TITLE
Updates documentation for custom locations

### PR DESCRIPTION
**Pull request by EmilePerron**
Documents the custom location feature implemented in plausible/analytics#1479.

### CODE REVIEW

**Comment by EmilePerron** [comment]
@ukutaht @metmarkosaric I wasn't quite sure where the new page on custom locations should be added in the sidebar, so I haven't added it yet.

What are your thoughts on that? 

Should it go under Getting Started or Goal conversions? Or maybe elsewhere?

**Comment by metmarkosaric** [comment]
we have some docs that are not part of the main sidebar so this one could be done like that too. a mention and a link from https://plausible.io/docs/script-extensions would be good to start with. it would still be searchable and i'll see if it needs to be added into the sidebar later on. thanks!

**Comment by EmilePerron** [comment]
@metmarkosaric Great! In that case, we're all set :)

**Comment by metmarkosaric** [comment]
great instructions! even i can follow them :) thanks @EmilePerron!

**Pull request merged**
