### PR TITLE
Add guide for proxying on CloudFront

### PR DESCRIPTION
**Pull request by thomasjsn**

### CODE REVIEW

**Comment by metmarkosaric** [comment]
nice, thank you!

**Comment by thomasjsn** [comment]
Update these as well?

* https://github.com/plausible/docs/blob/master/sidebars.js
* https://github.com/plausible/docs/blob/master/docs/proxy/introduction.md

**Comment by metmarkosaric** [comment]
i've just done it. i've also added this note to your instructions for those that use a different extension such as outbound link click tracking:

"Using our extensions such as hash-based routing, page exclusions or outbound link click tracking? Change the file name from script.js to the script you want to use: script.hash.js, script.exclusions.js or script.outbound-links.js. Want to use more than one extension? You can chain them like this: script.hash.exclusions.outbound-links.js."

**Comment by thomasjsn** [comment]
Nice :)

**Comment by ukutaht** [comment]
@thomasjsn Thank you so much! So many people are on AWS I'm sure this will be useful!

**Comment by ukutaht** [comment]
@thomasjsn Can I set this up even if I'm hosting my site somewhere else? Or does my site need to also be on S3/Cloudfront? Do you need to have your DNS nameservers pointing to Route 53?

I don't have much experience with AWS myself and it would be nice to list the requirements. I saw this was added to the _Standalone Proxy_ list and I'm just trying to clarify whether that's correct.

**Comment by thomasjsn** [comment]
@ukutaht My pleasure :)

You can use this to make your own "stats subdomain", and host the site elsewhere. To get it on the same domain as the website it needs to be hosted on CloudFront (which I think is quite obvious).

For DNS you can either use Route 53, when it will be an alias to the CloudFront distribution. Or use CNAME, or simply use the xxxxxxx.cloudfront.net domain provided by default.

So I would say this can be a standalone proxy 😃

**Comment by ukutaht** [comment]
Oh wonderful, that's neat. Let's keep it in the standalone category then. Again, thank you so much for this!

**Pull request merged**
