### PR TITLE
Add documentation for the Google Analytics import

### PR DESCRIPTION
**Pull request by m-col**
This adds docs for the Google Analytics import feature. The following
changes are included:

- A dedicated page on the feature aimed at users in the Website Settings
  section.
- Mention of removing imported data in the 'Reset your site data' and
  'Delete your site data' pages.
- A note on the filter-segments page informing the reader that imported
  data is not included when querying filtered data.
- Inclusion of imported data in the Stats API reference.
- Steps in the self-hosting docs for enabling the feature in Plausible.

-- 

I think I've covered all bases throughout the docs, but let me know if you think anything else needs adding!

### CODE REVIEW

**Comment by m-col** [comment]
AFAICT the check failures are unrelated:
```
12:48:48 PM: error @docusaurus/core@2.0.0-beta.14: The engine "node" is incompatible with this module. Expected version ">=14". Got "10.24.1"
12:48:48 PM: error Found incompatible module.
12:48:48 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
12:48:48 PM: Error during Yarn install
12:48:48 PM: Build was terminated: Build script returned non-zero exit code: 1
```

**Comment by metmarkosaric** [comment]
nice, thanks @m-col! looks great on the first review. i'll take a closer look and merge it all when we start getting the import ready for launch.

**Comment by ukutaht** [comment]
@metmarkosaric can this be closed? I think we have docs for this right?

**Comment by metmarkosaric** [comment]
> @metmarkosaric can this be closed? I think we have docs for this right?

it includes some changes to the self-hosted docs around the GA import too. is there a way to just merge the changes to `docs/self-hosting-configuration.md` and ignore everything else?

**Comment by ukutaht** [comment]
Yeah I'll do it when we release self-hosted

**Pull request closed without merging**
